### ISSUE TITLE
Error when installing offline

### ISSUE THREAD

**Issue by kuroshiba-Ginji** [codelibs/elasticsearch-analysis-fess#2]
I downloaded elasticsearch-analysis-fess folder and tried to install it offline (because I couldn't install them behind proxy).

And then I get this error.
Could you kindly tell me how to solve this?

`C:\elasticsearch-7.3.0\bin>elasticsearch-plugin install file:///C:folder/elasticsearch-analysis-fess-master.zip
-> Downloading file:///C:folder/elasticsearch-analysis-fess-master.zip
[=================================================] 100%??

Exception in thread "main" java.nio.file.NoSuchFileException: C:\elasticsearch-7.3.0\plugins\.installing-2888546492561074389\plugin-descriptor.properties
       
at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)   
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:235)
at java.base/java.nio.file.Files.newByteChannel(Files.java:373)
at java.base/java.nio.file.Files.newByteChannel(Files.java:424)
at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
at java.base/java.nio.file.Files.newInputStream(Files.java:158)
at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:156)
at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:723)
at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:802)
at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:785)
at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:231)
at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:216)
at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
at org.elasticsearch.cli.Command.main(Command.java:90)
at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)`

**Comment by marevol** [comment]
See [README](https://github.com/codelibs/elasticsearch-analysis-fess#version).

**Comment by kuroshiba-Ginji** [comment]
Thank you.
I had to add this below without double quotation mark.

`set ES_JAVA_OPTS=-Dhttp.proxyHost={proxy} -Dhttp.proxyPort={port} -Dhttps.proxyHost={proxy} -Dhttps.proxyPort={port}`

but still, it seams like I'm failing to download elasticsearch-minhash and elasticsearch-langfield.
